[package]
name = "datastruct"
repository = "https://github.com/elforjani13/datastruct/"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.204" ,features = ["derive"]}
serde_json = "1.0.120"
anyhow = "1.0.86"
base64 = "0.22.1"
nom = "7.1.3"
